[package]
name = "fujiya-macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
ash = { version = "0.38.0",  features = ["debug", "std"] }